name: Update HCL Code and Create Release

on:
  repository_dispatch:
    types:
      - version

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Version
        id: set_version
        run: echo "::set-output name=version::${{ github.event.client_payload.version }}"

      - name: Update HCL Code
        id: update_hcl_code
        run: |
          file="variables.tf"
          sed -i '/variable "tag" {/,/}/s/default = "7.11.5"/default = \"${{ steps.set_version.outputs.version }}\"/'

      - name: Update README version
        id: update_readme_version
        run: |
          file="README.md"
          echo "Updating $file"
          sed -i "s/version\s*=\s*\"[0-9.]*\"/version     = \"${{ steps.set_version.outputs.version }}\"/g" "$file"

      - name: Commit and Push Changes
        id: commit_and_push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "chore(version): bump to v${{ steps.set_version.outputs.version }}"
          git push
          echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ steps.commit_and_push.outputs.commit_hash }}
          tag_name: v${{ steps.set_version.outputs.version }}
          release_name: v${{ steps.set_version.outputs.version }}
          draft: false
