name: Create Release

on:
  repository_dispatch:
    types:
      - release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Release
        id: set_release
        run: echo "::set-output name=release::${{ github.event.client_payload.release }}"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: main
          tag_name: v${{ steps.set_release.outputs.release }}
          release_name: v${{ steps.set_release.outputs.release }}
          draft: false
